#!/usr/bin/env bash

# ============
# ASCII ANIMAL
# ============

# ANSI COLOUR CODES
RD='\x1B[0;31m'
GR='\x1B[0;32m'
YL='\x1B[1;33m'
OR='\x1B[0;33m'
BL='\x1B[0;34m'
LBL='\x1B[1;34m'
CY='\x1B[1;36m'
NC='\x1B[0m' # No Color

echo ""

# DUCK #####################################################################
# Adapted from: http://textart.io/art/tag/duck
duc1="                __           \n"
duc2="            ___( o)${OR}>${NC}         \n"
duc3="            \ <_. )    ${GR}V${NC}     \n"
duc4="        ${BL}~~~~~${NC}\`---'${BL}~~~~~${GR}|${BL}~~~${NC}"
duc="$duc1$duc2$duc3$duc4"

echo -e "$duc$NC"
