#!/usr/bin/env bash

# ============
# ASCII ANIMAL
# ============

# ANSI COLOUR CODES
RD='\x1B[0;31m'
GR='\x1B[0;32m'
YL='\x1B[1;33m'
OR='\x1B[0;33m'
BL='\x1B[0;34m'
LBL='\x1B[1;34m'
CY='\x1B[1;36m'
NC='\x1B[0m' # No Color

echo ""

# SQUIRREL ################################################################
# Adapted from: http://www.heartnsoul.com/ascii_art/squirrels.txt
squ1="${OR}        ,;;:;,          ${NC}\n"
squ2="${OR}          ;;;;;         ${NC}\n"
squ3="${OR}         ,:;;:;    ,'=. ${NC}\n"
squ4="${OR}         ;:;:;' .=\" ,'_\\\\${NC}\n"
squ5="${OR}         ':;:;,/  ,__:=${RD}@${NC}\n"
squ6="${OR}          ';;:;  =./)_  ${NC}\n"
squ7="${OR}            \`\"=\_  )_\"\` ${NC}\n"
squ8="${OR}                 \`\`'\"\`  ${NC}"
squ="$squ1$squ2$squ3$squ4$squ5$squ6$squ7$squ8"

echo -e "$squ$NC"
