#!/usr/bin/env bash

# ANSI COLOUR CODES
RD='\x1B[0;31m'
GR='\x1B[0;32m'
YL='\x1B[1;33m'
OR='\x1B[0;33m'
BL='\x1B[0;34m'
LBL='\x1B[1;34m'
CY='\x1B[1;36m'
NC='\x1B[0m' # No Color

echo ""
# DINOSAUR ##################################################################
# Adapted from: http://chris.com/ascii/index.php?art=animals/reptiles/dinosaurs
din1="${OR}                             __ ${NC}\n"
din2="${OR}                           / ${LBL}°${OR}_)${NC}\n"
din3="${OR}                _.----. _ /  /  ${NC}\n"
din4="${OR}              /           ../   ${NC}\n"
din5="${OR}          ___/ (   | ( ..|      ${NC}\n"
din6="${OR}        -------|_|--|_|         ${NC}"
din="$din1$din2$din3$din4$din5$din6"

echo -e "$din$NC"
