#!/usr/bin/env bash

# ANSI COLOUR CODES
RD='\x1B[0;31m'
GR='\x1B[0;32m'
YL='\x1B[1;33m'
OR='\x1B[0;33m'
BL='\x1B[0;34m'
LBL='\x1B[1;34m'
CY='\x1B[1;36m'
NC='\x1B[0m' # No Color

echo ""
liz1="${GR}          ${YL}O${GR}--${YL}O${GR}^^^^^^^^^^^^\________${NC}\n"
liz2="${GR}          \__/||-------||---------~${NC}"
liz="$liz1$liz2"
echo -e "$liz$NC"
