#!/usr/bin/env bash

INFO="\e[1;44m[ INFO ]\e[0m"
QDIR="$HOME/.local/bin/d_quarto"
DL_DIR="$HOME/.local/temp"
IDIR="$HOME/.local/bin"
VER=$2
LINK=$1

echo -e "\e[1mThis installs/updates Quarto $VER on your system.\e[0m"
read
if [[ ! -d "$DL_DIR" ]]; then
    echo -e "$INFO Creating DIR for Quarto@$DL_DIR"
    mkdir -p $DL_DIR/quarto
else
    rm -rf $DL_DIR/quarto/*
fi

if [[ -d "$QDIR" || -f "$IDIR/quarto" ]]; then
    echo -e "$INFO Removing previous Quarto installation."
    rm -rf $QDIR $IDIR/quarto*
fi

echo -e "$INFO Creating installation DIR for Quarto."
mkdir -p $QDIR

echo -e "$INFO Beginning installation/update of Quarto $VER"
wget $1 -O $DL_DIR/d_quarto.tar.gz
tar -C $QDIR -xvzf $DL_DIR/d_quarto.tar.gz
ln -s $QDIR/quarto-$VER/bin/quarto ~/.local/bin/quarto
rm -rf $DL_DIR/d_quarto.tar.gz

if [[ -x "$(command -v quarto check)" ]]; then
    echo -e "\e[1;42m[ SUCCESS ]\e[0m Quarto $VER updated/installed sucessfully."
    exit 0
else
    echo -e "\e[1;41m[ FAIL ]\e[0m Cannot update/install Quarto $VER."
    exit 1
fi
