syntax enable
set encoding=utf-8
set ruler
set iskeyword+=-
set mouse=a
set t_Co=256
set conceallevel=0
set tabstop=4
set shiftwidth=4
set smarttab
set smartindent
set expandtab
set autoindent
set laststatus=0
set number
set cursorline
set showtabline=4
set background=dark

colorscheme dracula
