# autogenerated by txs
#include:array
\__file_name=array.sty#S
\__file_seen_array.sty:#S
\__hook array#S
\__hook package/array/after#S
\__hook package/array/before#S
\__hook_next package/array/after#S
\__hook_next package/array/before#S
\g__hook_package/array/after_reversed_tl#S
\g__hook_package/array/before_reversed_tl#S
\unprocessedoptions-array.sty#S
array.sty#S
csnameendcsname#S
